// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eovfopjbfmwdsfcjmxsr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVvdmZvcGpiZm13ZHNmY2pteHNyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0OTk3MzAsImV4cCI6MjA3MzA3NTczMH0.tJ_SVRSMWIYAjiamYB3vfzzKjbQr86X7FbGNC3MGtK0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});